# Generated by Django 5.2.7 on 2025-10-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Área de Trabalho')),
            ],
            options={
                'verbose_name': 'Área de Trabalho',
                'verbose_name_plural': 'Áreas de Trabalho',
            },
        ),
    ]
