# Generated by Django 5.2.7 on 2025-11-06

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Esta migração foi convertida em NO-OP para evitar duplicação de colunas
    operations = [
    ]
