# Generated by Django 5.2.7 on 2025-11-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspace_dono_membros'),
        ('workspaces', '0003_workspace_dono_workspace_membros'),
    ]

    operations = [
    ]
