# Generated by Django 5.2.7 on 2025-11-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_set_dono_default_gutobielsantos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='membros',
        ),
    ]
