# Generated by Django 5.2.7 on 2025-11-06 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('workspaces', '0006_remove_workspace_membros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('accessible_boards', models.ManyToManyField(blank=True, related_name='member_access', to='boards.board', verbose_name='Pastas com Acesso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_members', to='workspaces.workspace', verbose_name='Área de Trabalho')),
            ],
            options={
                'verbose_name': 'Membro do Workspace',
                'verbose_name_plural': 'Membros dos Workspaces',
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
