# Generated by Django 5.2.7 on 2025-11-06 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_workspacemember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='shared_workspaces', through='workspaces.WorkspaceMember', to=settings.AUTH_USER_MODEL, verbose_name='Membros'),
        ),
    ]
