# Generated by Django 5.2.7 on 2025-10-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='First_name',
            field=models.CharField(default='Sem nome', max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Sem nome', max_length=100, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
    ]
