# Generated by Django 5.2.7 on 2025-10-21 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('anotacao', models.TextField(blank=True, null=True, verbose_name='Anotação')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Planilha')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='boards.board', verbose_name='Quadro')),
            ],
            options={
                'verbose_name': 'Planilha',
                'verbose_name_plural': 'Planilhas',
            },
        ),
    ]
