# Generated by Django 5.2.7 on 2025-11-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_sheet_colunas_sheet_linhas_sheet_tipo'),
        ('sheets', '0002_sheet_tipo_colunas_linhas'),
    ]

    operations = [
    ]
