# Generated by Django 5.2.7 on 2025-11-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_merge_20251110_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='linhas',
        ),
        migrations.AlterField(
            model_name='sheet',
            name='colunas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de dicionários com nome e editável de cada coluna (apenas para tipo genérico)', verbose_name='Configuração das Colunas'),
        ),
    ]
