# Generated by Django 5.2.7 on 2025-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_remove_sheet_linhas_alter_sheet_colunas'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='linhas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de linhas; cada linha é um dicionário onde a chave é o nome da coluna e o valor é o conteúdo', verbose_name='Linhas de Dados'),
        ),
    ]
