# Generated by Django 5.2.7 on 2025-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_column_row_cell'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='column',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='row',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='row',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='colunas',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='linhas',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='tipo',
        ),
        migrations.AddField(
            model_name='sheet',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='Row',
        ),
    ]
