# Generated by Django 5.2.7 on 2025-11-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0007_alter_column_unique_together_remove_column_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='template_type',
            field=models.CharField(choices=[('generico', 'Genérico'), ('contratos', 'Contratos'), ('colaboradores', 'Colaboradores'), ('produtos', 'Produtos')], default='generico', max_length=20, verbose_name='Tipo de Planilha'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='descricao',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descrição'),
        ),
    ]
