# Generated by Django 5.2.7 on 2025-11-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_sheet_template_type_alter_sheet_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='descricao',
            field=models.TextField(blank=True, default='Nenhuma descrição definida', null=True, verbose_name='Descrição'),
        ),
    ]
