# Generated by Django 5.2.7 on 2025-12-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0009_alter_sheet_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='descricao',
            field=models.TextField(default='Nenhuma descrição definida', verbose_name='Descrição'),
        ),
    ]
