# Generated by Django 5.2.7 on 2025-10-21 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor_unitario_anterior', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Unitário Anterior')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('valor_ipca', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor IPCA (%)')),
                ('valor_unitario_reajustado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Unitário Reajustado')),
                ('valor_total_reajustado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total Reajustado')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subelements', to='elements.element', verbose_name='Elemento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementos', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto do Elemento',
                'verbose_name_plural': 'Produtos do Elemento',
            },
        ),
    ]
