# Generated by Django 5.2.7 on 2025-10-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_contratoselement_elementfreelancer_and_more'),
        ('subElements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratosSubelement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Subelemento')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentários')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor_unitario_anterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_ipca', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor IPCA (%)')),
                ('valor_unitario_reajustado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_total_reajustado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subElements', to='elements.contratoselement')),
            ],
            options={
                'verbose_name': 'Subelemento Contratos',
                'verbose_name_plural': 'Subelementos Contratos',
            },
        ),
        migrations.CreateModel(
            name='SubElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('anotacao', models.TextField(blank=True, null=True, verbose_name='Anotação')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Subelemento')),
                ('colunas', models.JSONField(blank=True, default=dict, verbose_name='Colunas/Valores Dinâmicos')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subelements', to='elements.element', verbose_name='Elemento Pai')),
            ],
            options={
                'verbose_name': 'Subelemento Genérico',
                'verbose_name_plural': 'Subelementos Genéricos',
            },
        ),
        migrations.DeleteModel(
            name='ElementProduct',
        ),
    ]
