# Generated by Django 5.2.7 on 2025-10-21 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('file', models.FileField(upload_to='element_docs/', verbose_name='Arquivo')),
                ('nome', models.CharField(max_length=100, verbose_name='Documentação')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentacao', to='elements.element', verbose_name='Elemento')),
            ],
            options={
                'verbose_name': 'Arquivo de Documentação',
                'verbose_name_plural': 'Arquivos de Documentação',
            },
        ),
    ]
