# Generated by Django 5.2.7 on 2025-10-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_contratoselement_elementfreelancer_and_more'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='contratos_documentos/', verbose_name='Arquivo'),
        ),
        migrations.CreateModel(
            name='ContratosElementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contratos_documentos/')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentacao', to='elements.contratoselement')),
            ],
        ),
    ]
