# Generated by Django 5.2.7 on 2025-10-21 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Quadro')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='workspaces.workspace', verbose_name='Área de Trabalho')),
            ],
            options={
                'verbose_name': 'Quadro',
                'verbose_name_plural': 'Quadros',
            },
        ),
    ]
