# Generated by Django 5.2.7 on 2025-10-21 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('nome', models.CharField(max_length=100, verbose_name='Elemento')),
                ('empresa', models.CharField(max_length=50, verbose_name='Empresa')),
                ('objeto', models.CharField(max_length=150, verbose_name='Objeto')),
                ('qtd_total_itens', models.IntegerField(default=0, verbose_name='Qtd Total Itens')),
                ('valor_total_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total Anterior')),
                ('valor_total_reajustado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total Reajustado')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='sheets.sheet', verbose_name='Planilha')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
            },
        ),
        migrations.CreateModel(
            name='ElementCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Colaborador')),
                ('grossSalary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Email do Colaborador')),
                ('benefit_food', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Auxílio Alimentação')),
                ('benefit_transport', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Auxílio Transporte')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='elements.element', verbose_name='Elemento')),
            ],
            options={
                'verbose_name': 'Colaborador do Elemento',
                'verbose_name_plural': 'Colaboradores do Elemento',
            },
        ),
    ]
