# Generated by Django 5.2.7 on 2025-10-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratosElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('anotacao', models.TextField(blank=True, null=True, verbose_name='Anotação')),
                ('empresa', models.CharField(max_length=30, verbose_name='Empresa')),
                ('objeto', models.CharField(max_length=200, verbose_name='Objeto')),
                ('qtd_total_itens', models.IntegerField(default=0, verbose_name='Qtd Total Itens')),
                ('valor_total_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total Anterior')),
                ('valor_total_reajustado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total Reajustado')),
            ],
            options={
                'verbose_name': 'Elemento Contratos',
                'verbose_name_plural': 'Elementos Contratos',
            },
        ),
        migrations.CreateModel(
            name='ElementFreelancer',
            fields=[
                ('elementcollaborator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elements.elementcollaborator')),
            ],
            options={
                'verbose_name': 'Freelancer',
                'verbose_name_plural': 'Freelancers',
            },
            bases=('elements.elementcollaborator',),
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Elemento Genérico', 'verbose_name_plural': 'Elementos Genéricos'},
        ),
        migrations.RemoveField(
            model_name='element',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='element',
            name='objeto',
        ),
        migrations.RemoveField(
            model_name='element',
            name='qtd_total_itens',
        ),
        migrations.RemoveField(
            model_name='element',
            name='valor_total_anterior',
        ),
        migrations.RemoveField(
            model_name='element',
            name='valor_total_reajustado',
        ),
        migrations.AddField(
            model_name='element',
            name='anotacao',
            field=models.TextField(blank=True, null=True, verbose_name='Anotação'),
        ),
        migrations.AddField(
            model_name='element',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='element',
            name='colunas',
            field=models.JSONField(blank=True, default=dict, verbose_name='Colunas/Valores Dinâmicos'),
        ),
        migrations.AddField(
            model_name='element',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletado em'),
        ),
        migrations.AddField(
            model_name='elementcollaborator',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='elementcollaborator',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletado em'),
        ),
        migrations.AlterField(
            model_name='element',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Elemento'),
        ),
        migrations.AlterField(
            model_name='elementcollaborator',
            name='grossSalary',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salário bruto'),
        ),
    ]
