# Generated by Django 5.2.7 on 2025-11-10 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('elements', '0002_contratoselement_elementfreelancer_and_more'),
        ('sheets', '0004_remove_sheet_linhas_alter_sheet_colunas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratoselement',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='elementcollaborator',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.RemoveField(
            model_name='contratoselement',
            name='anotacao',
        ),
        migrations.RemoveField(
            model_name='contratoselement',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='contratoselement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contratoselement',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='contratoselement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='element',
            name='anotacao',
        ),
        migrations.RemoveField(
            model_name='element',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='element',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='element',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='element',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='element',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='elementcollaborator',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='elementcollaborator',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='elementcollaborator',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='elementcollaborator',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='elementcollaborator',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contratoselement',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='boards.board'),
        ),
        migrations.AddField(
            model_name='contratoselement',
            name='elemento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contratoselement',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_elements', to='sheets.sheet'),
        ),
        migrations.AddField(
            model_name='element',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='boards.board'),
        ),
        migrations.AddField(
            model_name='elementcollaborator',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='boards.board'),
        ),
        migrations.AddField(
            model_name='elementcollaborator',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='elementcollaborator',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_elements', to='sheets.sheet'),
        ),
        migrations.AlterField(
            model_name='contratoselement',
            name='empresa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contratoselement',
            name='objeto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contratoselement',
            name='qtd_total_itens',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='contratoselement',
            name='valor_total_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='contratoselement',
            name='valor_total_reajustado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='element',
            name='colunas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='element',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_elements', to='sheets.sheet'),
        ),
        migrations.AlterField(
            model_name='elementcollaborator',
            name='benefit_food',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Benefício Alimentação'),
        ),
        migrations.AlterField(
            model_name='elementcollaborator',
            name='benefit_transport',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Benefício Transporte'),
        ),
        migrations.AlterField(
            model_name='elementcollaborator',
            name='element',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='elementcollaborator',
            name='grossSalary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Salário Bruto'),
        ),
        migrations.CreateModel(
            name='ProductElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=100, verbose_name='Código')),
                ('nome', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome')),
                ('categoria', models.CharField(blank=True, default='', max_length=255, verbose_name='Categoria')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Preço')),
                ('estoque', models.IntegerField(blank=True, default=0, verbose_name='Estoque')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='boards.board')),
                ('sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_elements', to='sheets.sheet')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.DeleteModel(
            name='ElementFreelancer',
        ),
    ]
