# Generated by Django 5.2.7 on 2025-11-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_contratoselement_elementfreelancer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoselement',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente', 'Pendente'), ('concluido', 'Concluído')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
