# Generated by Django 5.2.7 on 2025-11-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_alter_contratoselement_options_and_more'),
        ('elements', '0003_contratoselement_status'),
    ]

    operations = [
    ]
