<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-12-02 18:47
=======
# Generated by Django 5.2.7 on 2025-11-25 18:43
>>>>>>> 097a7b36037ca8e7c5fa6d1fab43538e5c3c1a4b

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('elements', '0004_merge_20251125_1524'),
=======
        ('elements', '0004_merge_20251124_1554'),
>>>>>>> 097a7b36037ca8e7c5fa6d1fab43538e5c3c1a4b
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoselement',
            name='status',
        ),
    ]
