# Generated by Django 5.2.7 on 2025-11-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_merge_20251124_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoselement',
            name='status',
        ),
    ]
