# Generated by Django 5.2.7 on 2025-12-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_merge_20251125_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoselement',
            name='status',
        ),
    ]
