# Generated by Django 5.2.7 on 2025-11-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_valor_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
